apiVersion: v1
kind: Service
metadata:
  name: servercore-samples-2
  labels:
    app: servercore-samples-2
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: servercore-samples-2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servercore-samples-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servercore-samples-2
  template:
    metadata:
      labels:
        app: servercore-samples-2
      name: servercore
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - servercore-samples-2
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        beta.kubernetes.io/os: "windows"
        rke.cattle.io/windows-release-id: "1803"
      containers:
      - name: server
        image: microsoft/iis:windowsservercore-1803
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
