apiVersion: v1
kind: Service
metadata:
  name: test-curl-2
  labels:
    app: test-curl-2
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-curl-2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-curl-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-curl-2
  template:
    metadata:
      labels:
        app: test-curl-2
      name: test-curl-2
    spec:
      containers:
      - name: testcurl
        image: ewoutp/docker-nginx-curl:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
      nodeSelector:
        beta.kubernetes.io/os: linux
