apiVersion: v1
kind: Service
metadata:
  name: test-curl-1
  labels:
    app: test-curl-1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-curl-1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-curl-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-curl-1
  template:
    metadata:
      labels:
        app: test-curl-1
      name: test-curl-1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test-curl-2
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: testcurl
        image: ewoutp/docker-nginx-curl:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
      nodeSelector:
        beta.kubernetes.io/os: linux
